let lvls_ranks = [
	'parob', 
	'paprykowy patałach',
	'żółtodziób',
	'cieć pod folią',
	'świerzak',
	'szczur tunelowy',
	'początkujący',
	'nowicjusz',
	'praktykant',
	'farmer z przypadku',
	'paprykozbieracz z potencjałem',
	'początkujący rolnik',
	'paprykowy stażysta',
	'debiutant',
	'średniozaawansowany zbieracz',
	'zorientowny w temacie',
	'uzdolniony plantator',
	'sprawny zbieracz',
	'paprykowy hobbysta',
	'ambitny plantator papryki',
	'dojrzały zbieracz',
	'paprykowa głowa',
	'dozorca w szklarni',
	'paprykowy znachor',
	'paprykowy farmer',
	'paprykowy chomik',
	'biegły zbieracz papryki',
	'paprykowy stypendysta',
	'wschodząca gwiazda',
	'zawodowy hodowca papryki',
	'spragniony papryki',
	'kolekcjoner papryki',
	'fachowy rolnik',
	'paprykowe serce',
	'certyfikowany plantator papryki',
	'niestrudzony zbieracz',
	'paprykowy major',
	'profesjonalny zbieracz papryki',
	'utalentowny rolnik',
	'tańczący z papryką',
	'paprykowy ciułacz',
	'dziki plantator',
	'paprykowy makler',
	'paprykowy VIP',
	'zwierzchnik w szklarni',
	'zbieracz z pasji',
	'prawilny obywatel Dłuskiej Woli',
	'paprykowa krew',
	'potężny zbieracz',
	'naczelny polski paprykarz',
	'paprykowy maniak',
	'chodząca papryka',
	'wódz szklarni',
	'profesor papryka',
	'paprykowy boss',
	'prestiżowy hodowca papryki',
	'paprykowy oligarcha',
	'szklarniowy rekin',
	'paprykowy generał',
	'urodzony w papryce',
	'papykowy dominator',
	'paprykowa gwiazda',
	'książe papryki',
	'paprykowy marszałek',
	'paprykowy mocarz',
	'paprykowy fetyszysta',
	'paprykowy mędrzec',
	'Elon Musk pod folią',
	'burmistrz Dłuskiej Woli',
	'kapitan papryka',
	'paprykowy geniusz',
	'mistrz papryki',
	'paprykowy wirtuoz',
	'paprykowa znakomitość',
	'władca papryki',
	'prezydent Potworowa',
	'paprykowy Tony Stark',
	'paprykowy arcymistrz',
	'paprykowy autorytet',
	'król papryki',
	'paprykowy imperator',
	'paprykowy tytan',
	'paprykowa alfa i omega',
	'bóg papryki',
	'wielki mistrz R.',
];
